spring:
  application:
    name: LotusOJ

  datasource:
    url: jdbc:mysql://localhost:3306/oj_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: "xst61ez92rNSYQ0lcF8cOFI1R9MPpWf02fExM5YPvuc9NE0R6m1LntdmdiAx2ha4TaPfjaO9kgzKXKbdNHDExk"
  access-token-duration: 900
  refresh-token-duration: 604800